### ISSUE TITLE
Nice to know this project! However, would you like to add some contextual infos,such as...

### ISSUE THREAD

**Issue by asoboy** [sidooms/MovieTweetings#1]
Hi, sidooms! very glad to find this updating MovieTweetings dataset, very useful and convinient!! I cannot help adopting this into my recommender research, but finally I realize there are two problems I have to conquer, the first is the size of dataset, many public dataset is too huge to make use of on my laptop, moreover, I used to practice in Java. While yours rating files is just fabulous with the small size, thanks!! The second one is the absence of other infos, such as SNS matrix with time stamp, which is the ultimate problem I must solve, because I cannot view Twitter in my country, thus have no chance to crawl any tweets, so you my dear friend, may you add such contextual-like infos if you feel convinient,  this project is really promsing and robust, thanks!!

**Comment by sidooms** [comment]
Hi Asoboy,

Thanks for your comments. I'm very happy to hear that like this project. For now only basic data is included in the dataset, but I'm considering to publish the raw per tweet metadata as well. So for now keep an eye on this Github page for updates. By the way, the dataset as was released for the ACM RecSys Challenge 2014 will also be published here in the near future.

**Comment by mingyue-z** [comment]
Can't agree more with Asoboy! Very helpful to my research! I have been crawling rating data from Amazon reviews where the dataset is too sparse until I found your dataset. It's a very promising idea to extract rating data from Twitter, both the volume and the update speed. I'm sure your dataset will bring a new storm in the RS area. Plus: I cannot access to Twitter either in my country, so I have the same problem with Asoboy~~

**Comment by sidooms** [comment]
I just uploaded the RecSys Challenge 2014 dataset. If you combine the training, test and evaluation set you'll get over 200K rating tweets and their metadata as was used in the RecSys challenge this year.
