### ISSUE TITLE
Ratings for shows

### ISSUE THREAD

**Issue by DzmitryU** [sidooms/MovieTweetings#3]
Hello, everyone!
I've noticed, that MovieTweeting database is missing for TV-shows ratings (Game of Thrones, Breaking Bad, Vickings, Westworld, etc)
Is it possible to get ratings for shows from somewhere?

**Comment by sidooms** [comment]
Hi DzmitryU,

You're right, there are no TV-show ratings in the MovieTweetings dataset. At the time this was a deliberate choice to avoid confusion and to keep the format simple and compatible with similar datasets (like MovieLens).

You could easily setup your own tv-show collecting script though. You can find some example scripts [here](https://github.com/sidooms/Twitter-ratings).
