### ISSUE TITLE
items.dat == movies.dat ?

### ISSUE THREAD

**Issue by dzieciou** [sidooms/MovieTweetings#9]
https://github.com/sidooms/MovieTweetings/tree/master/latest contains `movies.dat`, while [README.md](https://github.com/sidooms/MovieTweetings/blob/master/README.md) talks about `items.dat`. 

I guess they are same file?

**Comment by sidooms** [comment]
Right, yep indeed 👍 . Funny how in 7 years I never noticed that :)
